# coding: utf-8

"""
    Synchronize API

    Synchronize API allows you to lipsync a video to any audio in any language.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from sync_labs_python_sdk import SyncLabs

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        synclabs = SyncLabs(
        
                        api_key = 'YOUR_API_KEY',
        )
        self.assertIsNotNone(synclabs)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
