# coding: utf-8

"""
    Synchronize API

    Synchronize API allows you to lipsync a video to any audio in any language.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import sync_labs_python_sdk
from sync_labs_python_sdk.model.video_initial import VideoInitial
from sync_labs_python_sdk import configuration


class TestVideoInitial(unittest.TestCase):
    """VideoInitial unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
