# coding: utf-8

"""
    Synchronize API

    Synchronize API allows you to lipsync a video to any audio in any language.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from sync_labs_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from sync_labs_python_sdk.api_response import AsyncGeneratorResponse
from sync_labs_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from sync_labs_python_sdk import schemas  # noqa: F401

from sync_labs_python_sdk.model.speak_initial import SpeakInitial as SpeakInitialSchema
from sync_labs_python_sdk.model.speak_dto import SpeakDto as SpeakDtoSchema

from sync_labs_python_sdk.type.speak_dto import SpeakDto
from sync_labs_python_sdk.type.speak_initial import SpeakInitial

from ...api_client import Dictionary
from sync_labs_python_sdk.pydantic.speak_dto import SpeakDto as SpeakDtoPydantic
from sync_labs_python_sdk.pydantic.speak_initial import SpeakInitial as SpeakInitialPydantic

from . import path

# body param
SchemaForRequestBodyApplicationJson = SpeakDtoSchema


request_body_speak_dto = api_client.RequestBody(
    content={
        'application/json': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJson),
    },
    required=True,
)
_auth = [
    'apiKey',
]
SchemaFor200ResponseBodyApplicationJson = SpeakInitialSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: SpeakInitial


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: SpeakInitial


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
    },
)
_status_code_to_response = {
    '200': _response_for_200,
}
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _speak_mapped_args(
        self,
        transcript: str,
        voice_id: str,
        max_credits: typing.Optional[typing.Union[int, float]] = None,
        webhook_url: typing.Optional[str] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _body = {}
        if transcript is not None:
            _body["transcript"] = transcript
        if voice_id is not None:
            _body["voiceId"] = voice_id
        if max_credits is not None:
            _body["maxCredits"] = max_credits
        if webhook_url is not None:
            _body["webhookUrl"] = webhook_url
        args.body = _body
        return args

    async def _aspeak_oapg(
        self,
        body: typing.Any = None,
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        used_path = path.value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/speak',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        serialized_data = request_body_speak_dto.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _speak_oapg(
        self,
        body: typing.Any = None,
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        used_path = path.value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/speak',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        serialized_data = request_body_speak_dto.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class SpeakRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def aspeak(
        self,
        transcript: str,
        voice_id: str,
        max_credits: typing.Optional[typing.Union[int, float]] = None,
        webhook_url: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._speak_mapped_args(
            transcript=transcript,
            voice_id=voice_id,
            max_credits=max_credits,
            webhook_url=webhook_url,
        )
        return await self._aspeak_oapg(
            body=args.body,
            **kwargs,
        )
    
    def speak(
        self,
        transcript: str,
        voice_id: str,
        max_credits: typing.Optional[typing.Union[int, float]] = None,
        webhook_url: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._speak_mapped_args(
            transcript=transcript,
            voice_id=voice_id,
            max_credits=max_credits,
            webhook_url=webhook_url,
        )
        return self._speak_oapg(
            body=args.body,
        )

class Speak(BaseApi):

    async def aspeak(
        self,
        transcript: str,
        voice_id: str,
        max_credits: typing.Optional[typing.Union[int, float]] = None,
        webhook_url: typing.Optional[str] = None,
        validate: bool = False,
        **kwargs,
    ) -> SpeakInitialPydantic:
        raw_response = await self.raw.aspeak(
            transcript=transcript,
            voice_id=voice_id,
            max_credits=max_credits,
            webhook_url=webhook_url,
            **kwargs,
        )
        if validate:
            return SpeakInitialPydantic(**raw_response.body)
        return api_client.construct_model_instance(SpeakInitialPydantic, raw_response.body)
    
    
    def speak(
        self,
        transcript: str,
        voice_id: str,
        max_credits: typing.Optional[typing.Union[int, float]] = None,
        webhook_url: typing.Optional[str] = None,
        validate: bool = False,
    ) -> SpeakInitialPydantic:
        raw_response = self.raw.speak(
            transcript=transcript,
            voice_id=voice_id,
            max_credits=max_credits,
            webhook_url=webhook_url,
        )
        if validate:
            return SpeakInitialPydantic(**raw_response.body)
        return api_client.construct_model_instance(SpeakInitialPydantic, raw_response.body)


class ApiForpost(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def apost(
        self,
        transcript: str,
        voice_id: str,
        max_credits: typing.Optional[typing.Union[int, float]] = None,
        webhook_url: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._speak_mapped_args(
            transcript=transcript,
            voice_id=voice_id,
            max_credits=max_credits,
            webhook_url=webhook_url,
        )
        return await self._aspeak_oapg(
            body=args.body,
            **kwargs,
        )
    
    def post(
        self,
        transcript: str,
        voice_id: str,
        max_credits: typing.Optional[typing.Union[int, float]] = None,
        webhook_url: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._speak_mapped_args(
            transcript=transcript,
            voice_id=voice_id,
            max_credits=max_credits,
            webhook_url=webhook_url,
        )
        return self._speak_oapg(
            body=args.body,
        )

