# coding: utf-8

"""
    Synchronize API

    Synchronize API allows you to lipsync a video to any audio in any language.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from sync_labs_python_sdk import schemas  # noqa: F401


class LipsyncDto(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "audioUrl",
            "videoUrl",
            "synergize",
        }
        
        class properties:
            audioUrl = schemas.StrSchema
            videoUrl = schemas.StrSchema
            synergize = schemas.BoolSchema
            maxCredits = schemas.NumberSchema
            webhookUrl = schemas.StrSchema
            model = schemas.StrSchema
            __annotations__ = {
                "audioUrl": audioUrl,
                "videoUrl": videoUrl,
                "synergize": synergize,
                "maxCredits": maxCredits,
                "webhookUrl": webhookUrl,
                "model": model,
            }
    
    audioUrl: MetaOapg.properties.audioUrl
    videoUrl: MetaOapg.properties.videoUrl
    synergize: MetaOapg.properties.synergize
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["audioUrl"]) -> MetaOapg.properties.audioUrl: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["videoUrl"]) -> MetaOapg.properties.videoUrl: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["synergize"]) -> MetaOapg.properties.synergize: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["maxCredits"]) -> MetaOapg.properties.maxCredits: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["webhookUrl"]) -> MetaOapg.properties.webhookUrl: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["model"]) -> MetaOapg.properties.model: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["audioUrl", "videoUrl", "synergize", "maxCredits", "webhookUrl", "model", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["audioUrl"]) -> MetaOapg.properties.audioUrl: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["videoUrl"]) -> MetaOapg.properties.videoUrl: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["synergize"]) -> MetaOapg.properties.synergize: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["maxCredits"]) -> typing.Union[MetaOapg.properties.maxCredits, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["webhookUrl"]) -> typing.Union[MetaOapg.properties.webhookUrl, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["model"]) -> typing.Union[MetaOapg.properties.model, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["audioUrl", "videoUrl", "synergize", "maxCredits", "webhookUrl", "model", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        audioUrl: typing.Union[MetaOapg.properties.audioUrl, str, ],
        videoUrl: typing.Union[MetaOapg.properties.videoUrl, str, ],
        synergize: typing.Union[MetaOapg.properties.synergize, bool, ],
        maxCredits: typing.Union[MetaOapg.properties.maxCredits, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        webhookUrl: typing.Union[MetaOapg.properties.webhookUrl, str, schemas.Unset] = schemas.unset,
        model: typing.Union[MetaOapg.properties.model, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'LipsyncDto':
        return super().__new__(
            cls,
            *args,
            audioUrl=audioUrl,
            videoUrl=videoUrl,
            synergize=synergize,
            maxCredits=maxCredits,
            webhookUrl=webhookUrl,
            model=model,
            _configuration=_configuration,
            **kwargs,
        )
