# coding: utf-8

"""
    Synchronize API

    Synchronize API allows you to lipsync a video to any audio in any language.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from sync_labs_python_sdk import schemas  # noqa: F401


class SpeakExtended(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "transcript_url",
            "credits_deducted",
            "id",
            "status",
        }
        
        class properties:
            id = schemas.StrSchema
            transcript_url = schemas.StrSchema
            status = schemas.StrSchema
            credits_deducted = schemas.NumberSchema
            audio_url = schemas.StrSchema
            __annotations__ = {
                "id": id,
                "transcript_url": transcript_url,
                "status": status,
                "credits_deducted": credits_deducted,
                "audio_url": audio_url,
            }
    
    transcript_url: MetaOapg.properties.transcript_url
    credits_deducted: MetaOapg.properties.credits_deducted
    id: MetaOapg.properties.id
    status: MetaOapg.properties.status
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["transcript_url"]) -> MetaOapg.properties.transcript_url: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["status"]) -> MetaOapg.properties.status: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["credits_deducted"]) -> MetaOapg.properties.credits_deducted: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["audio_url"]) -> MetaOapg.properties.audio_url: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["id", "transcript_url", "status", "credits_deducted", "audio_url", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["transcript_url"]) -> MetaOapg.properties.transcript_url: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["status"]) -> MetaOapg.properties.status: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["credits_deducted"]) -> MetaOapg.properties.credits_deducted: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["audio_url"]) -> typing.Union[MetaOapg.properties.audio_url, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["id", "transcript_url", "status", "credits_deducted", "audio_url", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        transcript_url: typing.Union[MetaOapg.properties.transcript_url, str, ],
        credits_deducted: typing.Union[MetaOapg.properties.credits_deducted, decimal.Decimal, int, float, ],
        id: typing.Union[MetaOapg.properties.id, str, ],
        status: typing.Union[MetaOapg.properties.status, str, ],
        audio_url: typing.Union[MetaOapg.properties.audio_url, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'SpeakExtended':
        return super().__new__(
            cls,
            *args,
            transcript_url=transcript_url,
            credits_deducted=credits_deducted,
            id=id,
            status=status,
            audio_url=audio_url,
            _configuration=_configuration,
            **kwargs,
        )
