# coding: utf-8

"""
    Synchronize API

    Synchronize API allows you to lipsync a video to any audio in any language.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class AnimateDto(BaseModel):
    # A url to the video file to be synchronized -- must be publicly accessible
    video_url: str = Field(alias='videoUrl')

    # A string of text to be spoken by the AI
    transcript: str = Field(alias='transcript')

    # The voice to use for audio generation
    voice_id: str = Field(alias='voiceId')

    # The model to use for video generation
    model: typing.Optional[str] = Field(None, alias='model')

    # Maximum number of credits to use for audio generation. If job exceeds this value, the job will be aborted
    max_credits: typing.Optional[typing.Union[int, float]] = Field(None, alias='maxCredits')

    # A url to send a notification to upon completion of audio generation
    webhook_url: typing.Optional[str] = Field(None, alias='webhookUrl')
    class Config:
        arbitrary_types_allowed = True
