# coding: utf-8

"""
    Synchronize API

    Synchronize API allows you to lipsync a video to any audio in any language.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class TranslationJobInitial(BaseModel):
    # A unique identifier for the translation job.
    id: str = Field(alias='id')

    # The original URL of the video that was submitted.
    original_video_url: str = Field(alias='original_video_url')

    # The status of the translation job.
    status: str = Field(alias='status')

    # The step of the translation job.
    step: str = Field(alias='step')

    # A URL which can be used to download the video.
    video_url: typing.Optional[str] = Field(None, alias='video_url')

    # The language into which the video is being translated.
    target_language: typing.Optional[str] = Field(None, alias='target_language')
    class Config:
        arbitrary_types_allowed = True
