# coding: utf-8

"""
    Synchronize API

    Synchronize API allows you to lipsync a video to any audio in any language.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from sync_labs_python_sdk.paths.animate.post import Animate
from sync_labs_python_sdk.paths.animate_cost.get import AnimateCost
from sync_labs_python_sdk.paths.animate_id.get import GetAnimation
from sync_labs_python_sdk.apis.tags.animate_api_raw import AnimateApiRaw


class AnimateApi(
    Animate,
    AnimateCost,
    GetAnimation,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: AnimateApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = AnimateApiRaw(api_client)
