# coding: utf-8

"""
    Synchronize API

    Synchronize API allows you to lipsync a video to any audio in any language.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from sync_labs_python_sdk.paths.animate.post import AnimateRaw
from sync_labs_python_sdk.paths.animate_cost.get import AnimateCostRaw
from sync_labs_python_sdk.paths.animate_id.get import GetAnimationRaw


class AnimateApiRaw(
    AnimateRaw,
    AnimateCostRaw,
    GetAnimationRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
