# coding: utf-8

"""
    Synchronize API

    Synchronize API allows you to lipsync a video to any audio in any language.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from sync_labs_python_sdk.paths.lipsync_id.get import GetLipsync
from sync_labs_python_sdk.paths.lipsync.post import LipSync
from sync_labs_python_sdk.paths.lipsync_cost.get import LipsyncCost
from sync_labs_python_sdk.apis.tags.lipsync_api_raw import LipsyncApiRaw


class LipsyncApi(
    GetLipsync,
    LipSync,
    LipsyncCost,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: LipsyncApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = LipsyncApiRaw(api_client)
