# coding: utf-8

"""
    Synchronize API

    Synchronize API allows you to lipsync a video to any audio in any language.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from sync_labs_python_sdk.paths.lipsync_id.get import GetLipsyncRaw
from sync_labs_python_sdk.paths.lipsync.post import LipSyncRaw
from sync_labs_python_sdk.paths.lipsync_cost.get import LipsyncCostRaw


class LipsyncApiRaw(
    GetLipsyncRaw,
    LipSyncRaw,
    LipsyncCostRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
