# coding: utf-8

"""
    Synchronize API

    Synchronize API allows you to lipsync a video to any audio in any language.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from sync_labs_python_sdk.paths.speak_id.get import GetSpeech
from sync_labs_python_sdk.paths.speak.post import Speak
from sync_labs_python_sdk.paths.speak_cost.get import SpeakCost
from sync_labs_python_sdk.apis.tags.speak_api_raw import SpeakApiRaw


class SpeakApi(
    GetSpeech,
    Speak,
    SpeakCost,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: SpeakApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = SpeakApiRaw(api_client)
