# coding: utf-8

"""
    Synchronize API

    Synchronize API allows you to lipsync a video to any audio in any language.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from sync_labs_python_sdk.paths.speak_id.get import GetSpeechRaw
from sync_labs_python_sdk.paths.speak.post import SpeakRaw
from sync_labs_python_sdk.paths.speak_cost.get import SpeakCostRaw


class SpeakApiRaw(
    GetSpeechRaw,
    SpeakRaw,
    SpeakCostRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
