# coding: utf-8

"""
    Synchronize API

    Synchronize API allows you to lipsync a video to any audio in any language.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from sync_labs_python_sdk.paths.translate_id.get import GetTranslation
from sync_labs_python_sdk.paths.translate.post import Translate
from sync_labs_python_sdk.paths.translate_cost.get import TranslationCost
from sync_labs_python_sdk.apis.tags.translate_api_raw import TranslateApiRaw


class TranslateApi(
    GetTranslation,
    Translate,
    TranslationCost,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: TranslateApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = TranslateApiRaw(api_client)
