# coding: utf-8

"""
    Synchronize API

    Synchronize API allows you to lipsync a video to any audio in any language.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from sync_labs_python_sdk.paths.translate_id.get import GetTranslationRaw
from sync_labs_python_sdk.paths.translate.post import TranslateRaw
from sync_labs_python_sdk.paths.translate_cost.get import TranslationCostRaw


class TranslateApiRaw(
    GetTranslationRaw,
    TranslateRaw,
    TranslationCostRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
