# coding: utf-8

"""
    Synchronize API

    Synchronize API allows you to lipsync a video to any audio in any language.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from sync_labs_python_sdk.paths.video_cost.get import CostRaw
from sync_labs_python_sdk.paths.video_id.get import GetLipSyncJobRaw
from sync_labs_python_sdk.paths.video.post import LipSyncRaw


class VideoApiRaw(
    CostRaw,
    GetLipSyncJobRaw,
    LipSyncRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
