# coding: utf-8

"""
    Synchronize API

    Synchronize API allows you to lipsync a video to any audio in any language.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from sync_labs_python_sdk.paths.video_cost.get import Cost
from sync_labs_python_sdk.paths.video_id.get import GetLipSyncJob
from sync_labs_python_sdk.paths.video.post import LipSync
from sync_labs_python_sdk.apis.tags.video_api_raw import VideoApiRaw


class VideoApi(
    Cost,
    GetLipSyncJob,
    LipSync,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: VideoApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = VideoApiRaw(api_client)
