# coding: utf-8

"""
    Synchronize API

    Synchronize API allows you to lipsync a video to any audio in any language.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from sync_labs_python_sdk.paths.voices.get import Voices
from sync_labs_python_sdk.apis.tags.voices_api_raw import VoicesApiRaw


class VoicesApi(
    Voices,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: VoicesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = VoicesApiRaw(api_client)
