# coding: utf-8

"""
    Synchronize API

    Synchronize API allows you to lipsync a video to any audio in any language.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredAnimateDto(TypedDict):
    # A url to the video file to be synchronized -- must be publicly accessible
    videoUrl: str

    # A string of text to be spoken by the AI
    transcript: str

    # The voice to use for audio generation
    voiceId: str

class OptionalAnimateDto(TypedDict, total=False):
    # The model to use for video generation
    model: str

    # Maximum number of credits to use for audio generation. If job exceeds this value, the job will be aborted
    maxCredits: typing.Union[int, float]

    # A url to send a notification to upon completion of audio generation
    webhookUrl: str

class AnimateDto(RequiredAnimateDto, OptionalAnimateDto):
    pass
