# coding: utf-8

"""
    Synchronize API

    Synchronize API allows you to lipsync a video to any audio in any language.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredLipsyncDto(TypedDict):
    # A url to the audio file to be synchronized -- must be publicly accessible
    audioUrl: str

    # A url to the video file to be synchronized -- must be publicly accessible
    videoUrl: str

    # A flag to enable / disable post-processing
    synergize: bool

class OptionalLipsyncDto(TypedDict, total=False):
    # Maximum number of credits to use for video generation. If job exceeds this value, the job will be aborted
    maxCredits: typing.Union[int, float]

    # A url to send a notification to upon completion of video generation
    webhookUrl: str

    # The model to use for video generation
    model: str

class LipsyncDto(RequiredLipsyncDto, OptionalLipsyncDto):
    pass
