# coding: utf-8

"""
    Synchronize API

    Synchronize API allows you to lipsync a video to any audio in any language.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredTranslationJobExtended(TypedDict):
    # A unique identifier for the translation job.
    id: str

    # A URL which can be used to download the audio.
    audio_url: str

    # The original URL of the video that was submitted.
    original_video_url: str

    # The source language of the video.
    source_language: str

    # The status of the translation job.
    status: str

    # The step of the translation job.
    step: str

class OptionalTranslationJobExtended(TypedDict, total=False):
    # A URL which can be used to download the video.
    video_url: str

    # A URL to access the transcript of the video.
    transcript_url: str

    # The language into which the video is being translated.
    target_language: str

class TranslationJobExtended(RequiredTranslationJobExtended, OptionalTranslationJobExtended):
    pass
